#!/usr/bin/env node
/**
 * Télécharge les images du manifest vers public/assets/images/
 * et génère src/lib/assets/localImages.ts pour usage offline.
 *
 * Usage: node scripts/download-images.mjs [--force]
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import https from "node:https";
import http from "node:http";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const MANIFEST_PATH = path.join(__dirname, "image-manifest.json");
const OUT_DIR = path.join(ROOT, "public", "assets", "images");
const GENERATED_TS = path.join(ROOT, "src", "lib", "assets", "localImages.ts");

const FORCE = process.argv.includes("--force");
const USER_AGENT =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36";

function downloadFile(url, dest, referer) {
  return new Promise((resolve, reject) => {
    const proto = url.startsWith("https") ? https : http;
    const file = fs.createWriteStream(dest);

    const request = proto.get(
      url,
      {
        headers: {
          "User-Agent": USER_AGENT,
          Accept: "image/*,*/*;q=0.8",
          ...(referer ? { Referer: referer } : {}),
        },
      },
      (response) => {
        if (
          response.statusCode &&
          response.statusCode >= 300 &&
          response.statusCode < 400 &&
          response.headers.location
        ) {
          file.close();
          fs.unlink(dest, () => {});
          downloadFile(response.headers.location, dest, referer)
            .then(resolve)
            .catch(reject);
          return;
        }

        if (response.statusCode !== 200) {
          file.close();
          fs.unlink(dest, () => {});
          reject(new Error(`HTTP ${response.statusCode} for ${url}`));
          return;
        }

        response.pipe(file);
        file.on("finish", () => {
          file.close(resolve);
        });
      },
    );

    request.on("error", (error) => {
      file.close();
      fs.unlink(dest, () => {});
      reject(error);
    });
  });
}

function writeGeneratedTs(entries) {
  const lines = entries
    .map(({ id, publicPath }) => `  "${id}": "${publicPath}",`)
    .join("\n");

  const content = `/** Auto-generated by scripts/download-images.mjs — do not edit manually */
export const LOCAL_IMAGES = {
${lines}
} as const;

export type LocalImageId = keyof typeof LOCAL_IMAGES;

export function getLocalImage(id: LocalImageId): string {
  return LOCAL_IMAGES[id];
}

export function getLocalImageOrFallback(
  id: LocalImageId,
  fallback: string,
): string {
  return LOCAL_IMAGES[id] ?? fallback;
}
`;

  fs.mkdirSync(path.dirname(GENERATED_TS), { recursive: true });
  fs.writeFileSync(GENERATED_TS, content, "utf8");
}

async function main() {
  const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf8"));
  const generated = [];

  fs.mkdirSync(OUT_DIR, { recursive: true });

  for (const item of manifest.images) {
    const dest = path.join(OUT_DIR, item.path);
    const publicPath = `/assets/images/${item.path}`;
    fs.mkdirSync(path.dirname(dest), { recursive: true });

    if (fs.existsSync(dest) && !FORCE) {
      console.log(`skip  ${item.id} (exists)`);
      generated.push({ id: item.id, publicPath });
      continue;
    }

    try {
      await downloadFile(item.url, dest, item.referer ?? "");
      const stat = fs.statSync(dest);
      if (stat.size < 512) {
        throw new Error(`file too small (${stat.size} bytes)`);
      }
      console.log(`ok    ${item.id} → ${item.path} (${stat.size} bytes)`);
      generated.push({ id: item.id, publicPath });
    } catch (error) {
      console.error(`fail  ${item.id}: ${error.message}`);
    }
  }

  writeGeneratedTs(generated);
  console.log(`\nGenerated ${GENERATED_TS}`);
  console.log(`Downloaded ${generated.length}/${manifest.images.length} images.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
